import {parseReceiptItems} from './receipt-core.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='receiptscan.data.v2'; let data=[]; let stream=null, reader=null, scanType='',nativeLoop=0;
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(Number(n)||0);
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dbPromise=new Promise((resolve,reject)=>{if(!indexedDB)return reject(Error('IndexedDB unavailable'));let q=indexedDB.open('ReceiptScanHistory',1);q.onupgradeneeded=()=>q.result.createObjectStore('state');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
async function loadData(){try{let db=await dbPromise;let r=await new Promise((ok,no)=>{let q=db.transaction('state').objectStore('state').get('receipts');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});data=Array.isArray(r)?r:JSON.parse(localStorage.getItem(KEY)||'[]')}catch{data=JSON.parse(localStorage.getItem(KEY)||'[]')}}
async function save(){localStorage.setItem(KEY,JSON.stringify(data));try{let db=await dbPromise;await new Promise((ok,no)=>{let q=db.transaction('state','readwrite').objectStore('state').put(data,'receipts');q.onsuccess=ok;q.onerror=()=>no(q.error)})}catch{}render()}
function parseItems(text){return parseReceiptItems(text)}
function render(){let q=($('#search')?.value||'').toLowerCase(), filtered=data.filter(r=>(r.merchant+' '+r.items.map(i=>i.name).join(' ')).toLowerCase().includes(q));let total=filtered.reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0);$('#summary').innerHTML=`<div class="metric"><small>Покупок</small><b>${filtered.length}</b></div><div class="metric"><small>Всего</small><b>${money(total)}</b></div><div class="metric"><small>Позиций</small><b>${filtered.reduce((s,r)=>s+r.items.length,0)}</b></div>`;$('#receipts').innerHTML=filtered.length?filtered.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<article class="card receipt"><div class="receipt-head"><div><b>${esc(r.merchant||'Без магазина')}</b><small>${r.date}</small></div><div><b>${money(r.items.reduce((s,i)=>s+i.qty*i.price,0))}</b><button data-del="${r.id}">Удалить</button></div></div><div class="items">${r.items.map(i=>`<div class="item"><span>${esc(i.name)} × ${i.qty}</span><span>${money(i.qty*i.price)}</span></div>`).join('')}</div>${r.note?`<small>${esc(r.note)}</small>`:''}</article>`).join(''):'<div class="empty">История покупок пока пуста.<br>Добавьте первый чек.</div>';renderStats()}
function renderStats(){let cats={};data.forEach(r=>r.items.forEach(i=>cats[i.cat]=(cats[i.cat]||0)+i.qty*i.price));let max=Math.max(1,...Object.values(cats));$('#statsBody').innerHTML=data.length?`<div class="summary"><div class="metric"><small>Чеков</small><b>${data.length}</b></div><div class="metric"><small>За месяц</small><b>${money(data.filter(r=>r.date.slice(0,7)===today().slice(0,7)).reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0))}</b></div></div><h3>Категории</h3>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="bar-card"><div class="receipt-head"><span>${esc(c)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}`:'<div class="empty">Аналитика появится после первой покупки.</div>'}
function showTab(id){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===id))}
function openForm(p={}){$('#merchant').value=p.merchant||'';$('#date').value=p.date||today();$('#itemsText').value=p.itemsText||'';$('#note').value=p.note||'';$('#editDialog').showModal()}
function stopCamera(){if(nativeLoop)cancelAnimationFrame(nativeLoop);nativeLoop=0;if(reader){try{reader.reset()}catch{}reader=null}stream?.getTracks().forEach(t=>t.stop());stream=null;$('#camera').pause?.();$('#camera').srcObject=null}
async function loadZXing(){if(window.ZXingBrowser)return;let urls=['https://unpkg.com/@zxing/browser@0.1.5/umd/zxing-browser.min.js','https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js'];for(let url of urls){try{await new Promise((ok,no)=>{let s=document.createElement('script');s.src=url;s.onload=ok;s.onerror=no;document.head.append(s)});if(window.ZXingBrowser)return}catch{}}throw Error('Не удалось загрузить сканер. Проверьте интернет-соединение')}
async function startScanner(){try{if(!window.isSecureContext)throw Error('Откройте сайт через HTTPS');if(!navigator.mediaDevices?.getUserMedia)throw Error('Safari не дал доступ к камере');stopCamera();$('#scannerStatus').textContent='Запрашиваю доступ к камере…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});let video=$('#camera');video.srcObject=stream;await video.play();if('BarcodeDetector'in window){try{let formats=['qr_code','ean_13','ean_8','code_128','upc_a','upc_e','code_39'];let detector=new BarcodeDetector({formats});$('#scannerStatus').textContent='Камера запущена. Наведите её на код…';let scan=async()=>{if(!stream)return;try{let found=await detector.detect(video);if(found?.length){let code=found[0].rawValue;stopCamera();$('#scannerDialog').close();openForm({merchant:scanType==='qr'?'Чек по QR':'Товар по штрихкоду',note:`${scanType==='qr'?'QR чека':'Штрихкод товара'}: ${code}`});return}}catch{}nativeLoop=requestAnimationFrame(scan)};nativeLoop=requestAnimationFrame(scan);return}catch{}}stream.getTracks().forEach(t=>t.stop());stream=null;await loadZXing();reader=new window.ZXingBrowser.BrowserMultiFormatReader();let devices=await reader.listVideoInputDevices();let device=devices.find(x=>/back|rear|environment|зад/i.test(x.label))||devices[devices.length-1];if(!device)throw Error('камера не найдена');$('#scannerStatus').textContent='Камера запущена. Наведите её на код…';reader.decodeFromVideoDevice(device.deviceId,'camera',(result)=>{if(result){let code=result.getText();stopCamera();$('#scannerDialog').close();openForm({merchant:scanType==='qr'?'Чек по QR':'Товар по штрихкоду',note:`${scanType==='qr'?'QR чека':'Штрихкод товара'}: ${code}`})}})}catch(e){stopCamera();$('#scannerStatus').textContent='Сканер не запустился: '+(e?.message||e)+'. Используйте фото кода или ручной ввод.'}}
$('#purchaseForm').addEventListener('submit',async e=>{e.preventDefault();let items=parseItems($('#itemsText').value);let note=$('#note').value.trim();if(!items.length&&!note)return alert('Добавьте товары или сначала сохраните результат QR/штрихкода');data.push({id:uid(),merchant:$('#merchant').value.trim(),date:$('#date').value,items,note});await save();$('#editDialog').close();showTab('home')});
$$('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#search').oninput=render;$('#addBtn').onclick=()=>openForm();$('#receipts').onclick=e=>{if(e.target.dataset.del){data=data.filter(x=>x.id!==e.target.dataset.del);save()}};
$$('[data-scan]').forEach(b=>b.onclick=()=>{scanType=b.dataset.scan;if(scanType==='manual')return openForm();if(scanType==='ocr')return $('#ocrDialog').showModal();$('#scannerTitle').textContent=scanType==='qr'?'Сканирование QR чека':'Сканирование штрихкода';$('#scannerDialog').showModal()});
$('#closeScanner').onclick=()=>{stopCamera();$('#scannerDialog').close()};$('#closeOcr').onclick=()=>$('#ocrDialog').close();$('#startCamera').onclick=startScanner;
$('#useCode').onclick=()=>{let code=$('#codeInput').value.trim();if(!code)return alert('Сначала отсканируйте или введите код');stopCamera();$('#scannerDialog').close();openForm({merchant:scanType==='qr'?'Чек по QR':'Товар по штрихкоду',note:`${scanType==='qr'?'QR чека':'Штрихкод товара'}: ${code}`})};
$('#photoInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{await loadZXing();let u=URL.createObjectURL(f),img=new Image();img.src=u;await img.decode();let r=await new window.ZXingBrowser.BrowserMultiFormatReader().decodeFromImageElement(img);$('#codeInput').value=r.getText();$('#scannerStatus').textContent='Код найден на фото. Нажмите «Использовать код».';URL.revokeObjectURL(u)}catch{$('#scannerStatus').textContent='Код на фото не найден. Попробуйте лучшее освещение или введите код вручную.'}};
$('#ocrInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('#ocrStatus').textContent='Загружаю OCR…';try{if(!window.Tesseract){let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';document.head.append(s);await new Promise((ok,no)=>{s.onload=ok;s.onerror=no})}$('#ocrStatus').textContent='Распознаю исходное фото…';let opts={logger:m=>{if(m.progress)$('#ocrStatus').textContent=`Распознавание: ${Math.round(m.progress*100)}%`},tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'};let out=await Tesseract.recognize(f,'rus+eng',opts);let text=out.data.text||'';if(text.trim().length<20){$('#ocrStatus').textContent='Улучшаю фото и повторяю распознавание…';let img=new Image();img.src=URL.createObjectURL(f);await img.decode();let scale=Math.min(2,1600/Math.max(img.width,img.height));let c=document.createElement('canvas'),w=Math.max(800,Math.round(img.width*scale)),h=Math.max(1000,Math.round(img.height*scale));c.width=w;c.height=h;let x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,w,h);let im=x.getImageData(0,0,w,h),d=im.data;for(let i=0;i<d.length;i+=4){let g=d[i]*.299+d[i+1]*.587+d[i+2]*.114;g=128+(g-128)*1.25;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);let second=await Tesseract.recognize(c,'rus+eng',opts);if((second.data.text||'').trim().length>text.trim().length)text=second.data.text;URL.revokeObjectURL(img.src)}$('#ocrText').value=text;$('#ocrStatus').textContent=text.trim()?'Текст распознан. Проверьте его перед разбором.':'Текст не найден. Попробуйте снять чек ближе, ровно и без бликов.'}catch(err){$('#ocrStatus').textContent='OCR не сработал: '+(err?.message||'ошибка загрузки').slice(0,140)+'. Можно вставить текст вручную.'}};
$('#parseOcr').onclick=()=>{let items=parseItems($('#ocrText').value);$('#ocrDialog').close();openForm({itemsText:items.map(i=>`${i.name}; ${i.qty}; ${i.price}; ${i.cat}`).join('\n'),note:'Распознано с фото. Проверьте все товары и цены.'})};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:2,data},null,2)],{type:'application/json'}));a.download='receipt-scan-history.json';a.click()};$('#importInput').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.data))throw Error();data=x.data;await save();alert(`Импортировано чеков: ${data.length}`)}catch{alert('Неверный файл истории')}};
window.addEventListener('online',()=>$('#online').textContent='Онлайн');window.addEventListener('offline',()=>$('#online').textContent='Офлайн — история хранится на устройстве');$('#online').textContent=navigator.onLine?'Онлайн':'Офлайн — история хранится на устройстве';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>deferred?.prompt();loadData().then(render);
