const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let stream=null, scanType='', scanTimer=null;
const KEY='receiptscan.data.v1'; let data=JSON.parse(localStorage.getItem(KEY)||'[]');
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10); const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));render()};
function parseItems(text){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{let p=line.split(';').map(x=>x.trim());if(p.length>=3)return{name:p[0],qty:Number(p[1])||1,price:Number(p[2].replace(',','.'))||0,cat:p[3]||'Другое'};let m=line.match(/^(.+?)\s+(\d+[,.]?\d*)\s*$/);return m?{name:m[1],qty:1,price:Number(m[2].replace(',','.')),cat:'Другое'}:null}).filter(Boolean)}
function render(){let q=($('#search')?.value||'').toLowerCase();let filtered=data.filter(r=>(r.merchant+' '+r.items.map(i=>i.name).join(' ')).toLowerCase().includes(q));let total=filtered.reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0);$('#summary').innerHTML=`<div class="metric"><small>Покупок</small><b>${filtered.length}</b></div><div class="metric"><small>Всего</small><b>${money(total)}</b></div><div class="metric"><small>Позиций</small><b>${filtered.reduce((s,r)=>s+r.items.length,0)}</b></div>`;$('#receipts').innerHTML=filtered.length?filtered.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<article class="card receipt"><div class="receipt-head"><div><b>${esc(r.merchant||'Без магазина')}</b><small>${r.date}</small></div><div><b>${money(r.items.reduce((s,i)=>s+i.qty*i.price,0))}</b><button data-del="${r.id}">Удалить</button></div></div><div class="items">${r.items.map(i=>`<div class="item"><span>${esc(i.name)} × ${i.qty}</span><span>${money(i.qty*i.price)}</span></div>`).join('')}</div>${r.note?`<small>${esc(r.note)}</small>`:''}</article>`).join(''):'<div class="empty">Покупок пока нет.<br>Добавьте чек через QR, фото или вручную.</div>';renderStats()}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderStats(){let cats={};data.forEach(r=>r.items.forEach(i=>cats[i.cat]=(cats[i.cat]||0)+i.qty*i.price));let max=Math.max(1,...Object.values(cats));$('#statsBody').innerHTML=data.length?`<div class="summary"><div class="metric"><small>Чеков</small><b>${data.length}</b></div><div class="metric"><small>За месяц</small><b>${money(data.filter(r=>r.date.slice(0,7)===today().slice(0,7)).reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0))}</b></div></div><h3>Категории</h3>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="bar-card"><div class="receipt-head"><span>${esc(c)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}`:'<div class="empty">Аналитика появится после добавления покупок.</div>'}
function openForm(pref={}){$('#merchant').value=pref.merchant||'';$('#date').value=pref.date||today();$('#itemsText').value=pref.itemsText||'';$('#note').value=pref.note||'';$('#editDialog').showModal()}
$('#purchaseForm').addEventListener('submit',e=>{e.preventDefault();let r={id:crypto.randomUUID(),merchant:$('#merchant').value.trim(),date:$('#date').value,items:parseItems($('#itemsText').value),note:$('#note').value.trim()};if(!r.items.length)return alert('Добавьте хотя бы один товар в формате: название; количество; цена; категория');data.push(r);save();$('#editDialog').close();showTab('home')});
function showTab(id){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===id))}
$$('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#search').oninput=render;$('#addBtn').onclick=()=>openForm();$('#receipts').onclick=e=>{let id=e.target.dataset.del;if(id){data=data.filter(x=>x.id!==id);save()}};
$$('[data-scan]').forEach(b=>b.onclick=()=>{scanType=b.dataset.scan;if(scanType==='manual')return openForm();if(scanType==='ocr')return $('#ocrDialog').showModal();$('#scannerTitle').textContent=scanType==='qr'?'Сканирование QR чека':'Сканирование штрихкода';$('#scannerDialog').showModal()});
$('#closeScanner').onclick=()=>{stopCamera();$('#scannerDialog').close()};$('#closeOcr').onclick=()=>$('#ocrDialog').close();function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('#camera').srcObject=null}
$('#startCamera').onclick=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Камера доступна только через HTTPS');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});$('#camera').srcObject=stream;$('#scannerStatus').textContent='Камера запущена. Наведите на код или введите его ниже.'}catch(e){$('#scannerStatus').textContent='Не удалось открыть камеру: '+e.message+'. Можно ввести код вручную.'}};
$('#useCode').onclick=()=>{let code=$('#codeInput').value.trim();if(!code)return;stopCamera();$('#scannerDialog').close();openForm({note:`Код: ${code}`})};
$('#photoInput').onchange=e=>{if(e.target.files[0]){$('#scannerStatus').textContent='Фото загружено. Для QR/штрихкода введите распознанный код вручную — автоматическое распознавание зависит от браузера.'}};
$('#ocrInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('#ocrStatus').textContent='Распознаю текст… на iPhone это может занять некоторое время.';try{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';document.head.append(s);await new Promise((ok,no)=>{s.onload=ok;s.onerror=no});let out=await Tesseract.recognize(f,'rus+eng',{logger:m=>{if(m.progress)$('#ocrStatus').textContent=`Распознавание: ${Math.round(m.progress*100)}%`}});$('#ocrText').value=out.data.text;$('#ocrStatus').textContent='Проверьте распознанный текст и нажмите «Разобрать».'}catch(err){$('#ocrStatus').textContent='OCR недоступен. Введите текст чека вручную.'}};
$('#parseOcr').onclick=()=>{let lines=$('#ocrText').value.split('\n').map(x=>x.trim()).filter(Boolean);let items=lines.map(x=>{let m=x.match(/^(.+?)\s+(\d+[,.]?\d*)$/);return m?`${m[1]}; 1; ${m[2].replace(',','.')}; Другое`:null}).filter(Boolean);$('#ocrDialog').close();openForm({itemsText:items.join('\n'),note:'Данные получены из OCR. Проверьте товары и цены.'})};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,data},null,2)],{type:'application/json'}));a.download='receipt-scan-backup.json';a.click()};$('#importInput').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.data))throw Error();data=x.data;save();alert('Данные импортированы')}catch{alert('Неверный файл резервной копии')}};
window.addEventListener('online',()=>$('#online').textContent='Онлайн');window.addEventListener('offline',()=>$('#online').textContent='Офлайн — данные сохраняются на устройстве');$('#online').textContent=navigator.onLine?'Онлайн':'Офлайн';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>deferred?.prompt();render();
