const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='receiptscan.data.v2'; let data=[]; let stream=null, reader=null, scanType='';
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dbPromise=new Promise((resolve,reject)=>{if(!indexedDB)return reject(Error('IndexedDB unavailable'));let q=indexedDB.open('ReceiptScanHistory',1);q.onupgradeneeded=()=>q.result.createObjectStore('state');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
async function loadData(){try{let db=await dbPromise;let r=await new Promise((ok,no)=>{let q=db.transaction('state').objectStore('state').get('receipts');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});data=Array.isArray(r)?r:JSON.parse(localStorage.getItem(KEY)||'[]')}catch{data=JSON.parse(localStorage.getItem(KEY)||'[]')}}
async function save(){localStorage.setItem(KEY,JSON.stringify(data));try{let db=await dbPromise;await new Promise((ok,no)=>{let q=db.transaction('state','readwrite').objectStore('state').put(data,'receipts');q.onsuccess=ok;q.onerror=()=>no(q.error)})}catch{}render()}
function parseItems(text){let out=[];for(let raw of text.split(/\n|\r/)){let line=raw.trim().replace(/\s+/g,' ');if(!line||/^(итого|всего|сумма|наличн|безнал|скидка|ндс|кассир|чек|спасибо)/i.test(line))continue;let p=line.split(';').map(x=>x.trim());if(p.length>=3){let price=Number(p[2].replace(/[^\d,.-]/g,'').replace(',','.'));if(price>0)out.push({name:p[0],qty:Number(p[1].replace(',','.'))||1,price,cat:p[3]||'Другое'});continue}let m=line.match(/^(.+?)\s+(\d+(?:[,.]\d+)?)\s*[xх×*]\s*(\d+(?:[,.]\d+)?)\s*(?:[=]\s*(\d+(?:[,.]\d+)?))?$/);if(m){let q=Number(m[2].replace(',','.')),unit=Number((m[4]||m[3]).replace(',','.'));out.push({name:m[1],qty:q,price:m[4]?unit/q:unit,cat:'Другое'});continue}m=line.match(/^(.+?)\s+(\d+[,.]?\d*)\s*(?:₽|руб\.?|р\.?)?$/i);if(m){let price=Number(m[2].replace(',','.'));if(price>0&&/[А-Яа-яA-Za-z]/.test(m[1]))out.push({name:m[1],qty:1,price,cat:'Другое'})}}return out}
function render(){let q=($('#search')?.value||'').toLowerCase(), filtered=data.filter(r=>(r.merchant+' '+r.items.map(i=>i.name).join(' ')).toLowerCase().includes(q));let total=filtered.reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0);$('#summary').innerHTML=`<div class="metric"><small>Покупок</small><b>${filtered.length}</b></div><div class="metric"><small>Всего</small><b>${money(total)}</b></div><div class="metric"><small>Позиций</small><b>${filtered.reduce((s,r)=>s+r.items.length,0)}</b></div>`;$('#receipts').innerHTML=filtered.length?filtered.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<article class="card receipt"><div class="receipt-head"><div><b>${esc(r.merchant||'Без магазина')}</b><small>${r.date}</small></div><div><b>${money(r.items.reduce((s,i)=>s+i.qty*i.price,0))}</b><button data-del="${r.id}">Удалить</button></div></div><div class="items">${r.items.map(i=>`<div class="item"><span>${esc(i.name)} × ${i.qty}</span><span>${money(i.qty*i.price)}</span></div>`).join('')}</div>${r.note?`<small>${esc(r.note)}</small>`:''}</article>`).join(''):'<div class="empty">История покупок пока пуста.<br>Добавьте первый чек.</div>';renderStats()}
function renderStats(){let cats={};data.forEach(r=>r.items.forEach(i=>cats[i.cat]=(cats[i.cat]||0)+i.qty*i.price));let max=Math.max(1,...Object.values(cats));$('#statsBody').innerHTML=data.length?`<div class="summary"><div class="metric"><small>Чеков</small><b>${data.length}</b></div><div class="metric"><small>За месяц</small><b>${money(data.filter(r=>r.date.slice(0,7)===today().slice(0,7)).reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.qty*i.price,0),0))}</b></div></div><h3>Категории</h3>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="bar-card"><div class="receipt-head"><span>${esc(c)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}`:'<div class="empty">Аналитика появится после первой покупки.</div>'}
function showTab(id){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===id))}
function openForm(p={}){$('#merchant').value=p.merchant||'';$('#date').value=p.date||today();$('#itemsText').value=p.itemsText||'';$('#note').value=p.note||'';$('#editDialog').showModal()}
function stopCamera(){if(reader){try{reader.reset()}catch{}reader=null}stream?.getTracks().forEach(t=>t.stop());stream=null;$('#camera').srcObject=null}
async function loadZXing(){if(window.ZXingBrowser)return;await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://unpkg.com/@zxing/browser@0.1.5/umd/zxing-browser.min.js';s.onload=ok;s.onerror=no;document.head.append(s)})}
async function startScanner(){try{if(!window.isSecureContext)throw Error('Откройте сайт через HTTPS');if(!navigator.mediaDevices?.getUserMedia)throw Error('Браузер не дал доступ к камере');await loadZXing();let C=window.ZXingBrowser.BrowserMultiFormatReader;reader=new C();let devices=await C.listVideoInputDevices();let device=(devices.find(x=>/back|environment|зад/i.test(x.label))||devices[devices.length-1]);if(!device)throw Error('Камера не найдена');$('#scannerStatus').textContent='Наведите камеру на QR-код или штрихкод';reader.decodeFromVideoDevice(device.deviceId,'camera',(result,err)=>{if(result){let code=result.getText();$('#codeInput').value=code;$('#scannerStatus').textContent='Код распознан. Нажмите «Использовать код».';stopCamera()}})}catch(e){$('#scannerStatus').textContent='Сканер недоступен: '+e.message+'. Введите код вручную или загрузите фото.'}}
$('#purchaseForm').addEventListener('submit',async e=>{e.preventDefault();let items=parseItems($('#itemsText').value);if(!items.length)return alert('Не нашёл товарные строки. Используйте формат: Молоко; 2; 89,90; Молочные продукты');data.push({id:crypto.randomUUID(),merchant:$('#merchant').value.trim(),date:$('#date').value,items,note:$('#note').value.trim()});await save();$('#editDialog').close();showTab('home')});
$$('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#search').oninput=render;$('#addBtn').onclick=()=>openForm();$('#receipts').onclick=e=>{if(e.target.dataset.del){data=data.filter(x=>x.id!==e.target.dataset.del);save()}};
$$('[data-scan]').forEach(b=>b.onclick=()=>{scanType=b.dataset.scan;if(scanType==='manual')return openForm();if(scanType==='ocr')return $('#ocrDialog').showModal();$('#scannerTitle').textContent=scanType==='qr'?'Сканирование QR чека':'Сканирование штрихкода';$('#scannerDialog').showModal()});
$('#closeScanner').onclick=()=>{stopCamera();$('#scannerDialog').close()};$('#closeOcr').onclick=()=>$('#ocrDialog').close();$('#startCamera').onclick=startScanner;
$('#useCode').onclick=()=>{let code=$('#codeInput').value.trim();if(!code)return alert('Сначала отсканируйте или введите код');stopCamera();$('#scannerDialog').close();openForm({note:`${scanType==='qr'?'QR чека':'Штрихкод товара'}: ${code}`})};
$('#photoInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{await loadZXing();let u=URL.createObjectURL(f),img=new Image();img.src=u;await img.decode();let r=await new window.ZXingBrowser.BrowserMultiFormatReader().decodeFromImageElement(img);$('#codeInput').value=r.getText();$('#scannerStatus').textContent='Код найден на фото. Нажмите «Использовать код».';URL.revokeObjectURL(u)}catch{$('#scannerStatus').textContent='Код на фото не найден. Попробуйте лучшее освещение или введите код вручную.'}};
$('#ocrInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('#ocrStatus').textContent='Распознаю текст…';try{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';document.head.append(s);await new Promise((ok,no)=>{s.onload=ok;s.onerror=no});let out=await Tesseract.recognize(f,'rus+eng',{logger:m=>{if(m.progress)$('#ocrStatus').textContent=`Распознавание: ${Math.round(m.progress*100)}%`}});$('#ocrText').value=out.data.text;$('#ocrStatus').textContent='Проверьте текст и нажмите «Разобрать».'}catch{$('#ocrStatus').textContent='OCR не загрузился. Вставьте текст чека вручную.'}};
$('#parseOcr').onclick=()=>{let items=parseItems($('#ocrText').value);$('#ocrDialog').close();openForm({itemsText:items.map(i=>`${i.name}; ${i.qty}; ${i.price}; ${i.cat}`).join('\n'),note:'Распознано с фото. Проверьте все товары и цены.'})};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:2,data},null,2)],{type:'application/json'}));a.download='receipt-scan-history.json';a.click()};$('#importInput').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.data))throw Error();data=x.data;await save();alert(`Импортировано чеков: ${data.length}`)}catch{alert('Неверный файл истории')}};
window.addEventListener('online',()=>$('#online').textContent='Онлайн');window.addEventListener('offline',()=>$('#online').textContent='Офлайн — история хранится на устройстве');$('#online').textContent=navigator.onLine?'Онлайн':'Офлайн — история хранится на устройстве';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>deferred?.prompt();loadData().then(render);
